import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Check, ChevronDown, Headphones, Layers3, Menu, ShieldCheck, Sparkles, Wallet, X, Zap } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useTranslation } from '../lib/i18n';
import { useAuth } from '../contexts/AuthContext';
import toast from 'react-hot-toast';

const PLATFORMS = [['Instagram','IG'],['TikTok','TK'],['YouTube','YT'],['Facebook','FB'],['Telegram','TG'],['X / Twitter','X'],['Spotify','SP'],['Threads','TH']];
const FAQ_EN = [
 ['What is RapidSMM?','RapidSMM is a social media marketing panel where you can discover services, fund your wallet, place orders and track them from one dashboard.'],
 ['How do I place my first order?','Create an account, add funds, choose a category, select a service, enter the target information and quantity when required, then submit the order.'],
 ['Do I need to share my social password?','No. Never share your social account password. Services should only use the target URL or other information explicitly required by that service.'],
 ['Can I use RapidSMM as a reseller?','Yes. The panel includes an API designed for resellers and software integrations, plus provider synchronization and service management.'],
 ['What currency is the wallet?','USD is the primary RapidSMM wallet currency. External payment methods can settle in their own currency and are converted before wallet credit.']
];
const FAQ_AR = [
 ['إيه هو RapidSMM؟','RapidSMM لوحة متخصصة لإدارة خدمات التسويق على السوشيال ميديا. تقدر تستكشف الخدمات، تضيف رصيد، تعمل طلبات وتتابعها من مكان واحد.'],
 ['إزاي أعمل أول طلب؟','اعمل حساب، أضف رصيد، اختار القسم ثم الخدمة، اكتب بيانات الهدف والكمية لو مطلوبة، وبعدها أرسل الطلب.'],
 ['هل لازم أدي باسورد حساب السوشيال؟','لا. ممنوع تشارك باسورد حسابك. الخدمة بتحتاج فقط الرابط أو البيانات المطلوبة منها بشكل واضح.'],
 ['هل ينفع أستخدم RapidSMM كموزع؟','أيوه. المنصة فيها API للموزعين والتكاملات البرمجية، بالإضافة لمزامنة المزودين وإدارة الخدمات.'],
 ['عملة المحفظة إيه؟','عملة المحفظة الأساسية هي USD. طرق الدفع الخارجية ممكن تستخدم عملة مختلفة ويتم تحويلها قبل إضافة الرصيد.']
];

export default function LandingPage(){
 const {dir}=useTranslation(); const ar=dir==='rtl'; const navigate=useNavigate();
 const {user,registerWithEmail,loginWithEmail,resetPassword}=useAuth();
 const [menu,setMenu]=useState(false); const [auth,setAuth]=useState<'login'|'register'|null>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [referralCode,setReferralCode]=useState(''); const [faq,setFaq]=useState(0);
 const referralFromUrl=useMemo(()=>new URLSearchParams(window.location.search).get('ref')?.trim().toUpperCase()||localStorage.getItem('ref')||'',[]);
 React.useEffect(()=>{if(referralFromUrl){setReferralCode(referralFromUrl);setAuth('register');}},[referralFromUrl]);
 const {data:showcase}=useQuery({queryKey:['public-showcase'],queryFn:async()=>{const r=await fetch('/api/public/showcase');return r.json()},retry:1});
 const {data:config}=useQuery({queryKey:['client-config'],queryFn:async()=>{const r=await fetch('/api/client/config');return r.json()},retry:1});
 const services=showcase?.services||[]; const serviceCount=Number(showcase?.serviceCount||0); const categoryCount=Number(showcase?.categoryCount||0); const faqs=ar?FAQ_AR:FAQ_EN;
 const text=ar?{
  navServices:'الخدمات',navHow:'إزاي بيشتغل؟',navBlog:'المدونة',navSupport:'الدعم',dashboard:'لوحة التحكم',login:'تسجيل الدخول',start:'ابدأ مجانًا',
  badge:'منصة SMM بسيطة للمبتدئين والموزعين',title:'كبّر حضورك على السوشيال. من مكان واحد.',copy:'استكشف الخدمات، أضف رصيدك، اعمل طلبك وتابع حالته بسهولة — بدون تعقيد أو خطوات زيادة.',browse:'استكشف الخدمات',how:'إزاي تبدأ؟',howCopy:'3 خطوات واضحة من أول تسجيل الحساب لحد متابعة الطلب.',create:'اعمل حساب',fund:'أضف رصيد',order:'اختار الخدمة واعمل الطلب',proof:['محفظة USD','مزامنة مزودين','API للموزعين','دعم وتذاكر'],live:'الخدمات المتاحة',cats:'الأقسام',wallet:'عملة المحفظة',access:'الوصول',platformTitle:'خدمات للمنصات اللي بتستخدمها',platformCopy:'من Instagram وTikTok لحد YouTube وTelegram — استكشف الكتالوج حسب احتياجك.',featuresTitle:'كل اللي تحتاجه في لوحة واحدة',featuresCopy:'واجهة واضحة للمستخدم الجديد، وأدوات عملية للموزعين وإدارة الطلبات.',pricing:'كتالوج الخدمات',pricingCopy:'الأسعار والحدود بتتحدد من لوحة الإدارة وبتتزامن مع المزودين المتصلين.',openCatalog:'فتح الكتالوج',faqTitle:'أسئلة شائعة',faqCopy:'إجابات مختصرة على أهم الأسئلة قبل ما تبدأ.',ctaTitle:'جاهز تبدأ؟',ctaCopy:'اعمل حساب مجاني واستكشف الخدمات المتاحة دلوقتي.',cta:'إنشاء حساب',loginTitle:'تسجيل الدخول',registerTitle:'إنشاء حساب',name:'الاسم',email:'البريد الإلكتروني',password:'كلمة المرور',ref:'كود الإحالة',optional:'اختياري',submitLogin:'دخول',submitRegister:'إنشاء الحساب',already:'عندك حساب؟',newUser:'لسه جديد؟',close:'إغلاق',forgot:'نسيت كلمة المرور؟',resetSent:'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك.',
 }:{
  navServices:'Services',navHow:'How it works',navBlog:'Blog',navSupport:'Support',dashboard:'Dashboard',login:'Sign in',start:'Start free',
  badge:'A simple SMM platform for beginners & resellers',title:'Grow your social presence. From one place.',copy:'Explore services, fund your wallet, place orders and track progress — without unnecessary steps.',browse:'Explore services',how:'How it works',howCopy:'Three clear steps from account creation to order tracking.',create:'Create an account',fund:'Add funds',order:'Choose a service & order',proof:['USD wallet','Provider sync','Reseller API','Tickets & support'],live:'Live services',cats:'Categories',wallet:'Wallet currency',access:'Access',platformTitle:'Services for the platforms you use',platformCopy:'From Instagram and TikTok to YouTube and Telegram — browse the catalog by your goal.',featuresTitle:'Everything in one panel',featuresCopy:'A clear experience for new customers, with practical tools for resellers and order management.',pricing:'Service catalog',pricingCopy:'Prices and limits are managed from admin and can be synchronized from connected providers.',openCatalog:'Open catalog',faqTitle:'Frequently asked questions',faqCopy:'Quick answers to the most important questions before you start.',ctaTitle:'Ready to get started?',ctaCopy:'Create a free account and explore the available services.',cta:'Create account',loginTitle:'Sign in',registerTitle:'Create account',name:'Name',email:'Email',password:'Password',ref:'Referral code',optional:'optional',submitLogin:'Sign in',submitRegister:'Create account',already:'Already have an account?',newUser:'New here?',close:'Close',forgot:'Forgot password?',resetSent:'Password reset link sent to your email.'
 };
 const handleReset=async()=>{try{if(!email.trim())throw new Error(ar?'اكتب بريدك الإلكتروني أولاً.':'Enter your email first.');await resetPassword(email.trim());toast.success(text.resetSent)}catch(err:any){toast.error(err?.message||'Unable to send reset link')}};
 const handleAuth=async(e:React.FormEvent)=>{e.preventDefault();try{if(auth==='register'){if(!name.trim()||password.length<8)throw new Error(ar?'اكتب اسمك وكلمة مرور 8 أحرف على الأقل.':'Enter your name and an 8+ character password.');if(!referralFromUrl&&referralCode)localStorage.setItem('ref',referralCode.trim().toUpperCase());await registerWithEmail(email.trim(),password,name.trim());toast.success(ar?'تم إنشاء الحساب. تحقق من بريدك الإلكتروني لتأكيد الحساب.':'Account created. Check your email to verify your account.')}else await loginWithEmail(email.trim(),password);setAuth(null);navigate('/dashboard',{replace:true})}catch(err:any){toast.error(err?.message||'Authentication failed')}};
 const scrollHow=(e:React.MouseEvent)=>{e.preventDefault();setMenu(false);document.getElementById('how')?.scrollIntoView({behavior:'smooth'})};
 return <div className="landing-shell" dir={dir}>
  <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-4 sm:px-6">
   <Link to="/" className="flex items-center gap-3" onClick={()=>setMenu(false)}><span className="brand-mark">R</span><span className="text-xl font-black tracking-tight">Rapid<span className="text-violet-600">SMM</span></span></Link>
   <nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 md:flex"><Link className="landing-nav-link" to="/services">{text.navServices}</Link><a className="landing-nav-link" href="#how" onClick={scrollHow}>{text.navHow}</a><Link className="landing-nav-link" to="/blog">{text.navBlog}</Link><Link className="landing-nav-link" to="/support">{text.navSupport}</Link></nav>
   <div className="hidden items-center gap-2 md:flex">{user?<Link to="/dashboard" className="btn-primary">{text.dashboard}<ArrowRight size={15}/></Link>:<><button className="btn-ghost" onClick={()=>setAuth('login')}>{text.login}</button><button className="btn-primary" onClick={()=>setAuth('register')}>{text.start}<ArrowRight size={15}/></button></>}</div>
   <button className="rounded-xl bg-slate-100 p-2 md:hidden" onClick={()=>setMenu(!menu)} aria-label="menu">{menu?<X/>:<Menu/>}</button>
  </div>{menu&&<div className="border-t border-slate-200 bg-white p-4 md:hidden"><div className="mx-auto flex max-w-md flex-col gap-2"><Link onClick={()=>setMenu(false)} className="mobile-nav" to="/services">{text.navServices}</Link><a onClick={scrollHow} className="mobile-nav" href="#how">{text.navHow}</a><Link onClick={()=>setMenu(false)} className="mobile-nav" to="/blog">{text.navBlog}</Link><Link onClick={()=>setMenu(false)} className="mobile-nav" to="/support">{text.navSupport}</Link>{user?<Link onClick={()=>setMenu(false)} className="btn-primary justify-center" to="/dashboard">{text.dashboard}</Link>:<><button onClick={()=>{setMenu(false);setAuth('login')}} className="btn-ghost">{text.login}</button><button onClick={()=>{setMenu(false);setAuth('register')}} className="btn-primary">{text.start}</button></>}</div></div>}</header>
  <main>
   <section className="landing-hero"><div className="landing-hero-grid"/><div className="relative mx-auto grid max-w-[1240px] gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28"><div>
    <div className="landing-badge"><Sparkles size={14}/>{text.badge}</div><h1 className="mt-6">{text.title}</h1><p className="landing-hero-copy mt-6">{text.copy}</p>
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>setAuth('register')} className="btn-primary !px-6 !py-3.5">{text.start}<ArrowRight size={17}/></button><Link to="/services" className="btn-ghost !border-white/10 !bg-white/5 !text-white !px-6 !py-3.5">{text.browse}</Link></div>
    <div className="landing-proof mt-8">{text.proof.map(x=><span key={x}><Check size={13} className="inline mr-1"/>{x}</span>)}</div>
   </div><div className="landing-demo"><div className="mb-4 flex items-center justify-between"><div><small className="text-[10px] font-bold uppercase tracking-wider text-slate-500">RapidSMM</small><h3 className="text-lg font-black text-white">{ar?'تجربة الطلب':'Order flow'}</h3></div><span className="rounded-full bg-emerald-400/15 px-2.5 py-1 text-[10px] font-black text-emerald-300">● Live</span></div><div className="space-y-3"><div className="landing-demo-step"><small>{ar?'1 — القسم':'1 — Category'}</small><div className="landing-demo-value">Instagram</div></div><div className="landing-demo-step"><small>{ar?'2 — الخدمة':'2 — Service'}</small><div className="landing-demo-value">{ar?'متابعين Instagram — جودة عالية':'Instagram Followers — High Quality'}</div></div><div className="grid grid-cols-2 gap-3"><div className="landing-demo-step"><small>{ar?'الكمية':'Quantity'}</small><div className="landing-demo-value">1,000</div></div><div className="landing-demo-step"><small>{ar?'التكلفة':'Charge'}</small><div className="landing-demo-value text-violet-200">$2.84</div></div></div></div><div className="mt-4 rounded-2xl bg-violet-500/15 p-3 text-xs text-violet-100">{ar?'اختار القسم ثم الخدمة — وكل التفاصيل المهمة هتظهر قدامك قبل إرسال الطلب.':'Choose a category, then a service. The important details are shown before you submit.'}</div></div></div></section>
   <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-[1240px] grid-cols-2 gap-4 px-4 py-7 sm:grid-cols-4 sm:px-6"><div className="text-center"><b className="text-xl font-black">{serviceCount||'—'}</b><span className="mt-1 block text-xs font-bold text-slate-500">{text.live}</span></div><div className="text-center"><b className="text-xl font-black">{categoryCount||'—'}</b><span className="mt-1 block text-xs font-bold text-slate-500">{text.cats}</span></div><div className="text-center"><b className="text-xl font-black">USD</b><span className="mt-1 block text-xs font-bold text-slate-500">{text.wallet}</span></div><div className="text-center"><b className="text-xl font-black">24/7</b><span className="mt-1 block text-xs font-bold text-slate-500">{text.access}</span></div></div></section>
   <section className="landing-section"><div className="max-w-2xl"><p className="mb-2 text-xs font-black tracking-[.16em] text-violet-600">PLATFORMS</p><h2>{text.platformTitle}</h2><p className="landing-muted mt-4">{text.platformCopy}</p></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{PLATFORMS.map(([n,i])=><Link key={n} to="/services" className="landing-platform"><b>{i}</b><span className="truncate">{n}</span></Link>)}</div></section>
   <section id="how" className="bg-white"><div className="landing-section"><div className="max-w-2xl"><p className="mb-2 text-xs font-black tracking-[.16em] text-violet-600">{text.how}</p><h2>{text.howCopy}</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="landing-card"><div className="landing-number">01</div><h3 className="mt-5 text-lg font-black">{text.create}</h3><p className="landing-muted mt-2">{ar?'حسابك مجاني وتقدر تدخل على لوحة التحكم فورًا.':'Create a free account and access your dashboard.'}</p></div><div className="landing-card"><div className="landing-number">02</div><h3 className="mt-5 text-lg font-black">{text.fund}</h3><p className="landing-muted mt-2">{ar?'أضف الرصيد بطريقة الدفع المتاحة، وبعدها استخدم محفظتك في الطلبات.':'Add funds using an available payment method, then use your wallet for orders.'}</p></div><div className="landing-card"><div className="landing-number">03</div><h3 className="mt-5 text-lg font-black">{text.order}</h3><p className="landing-muted mt-2">{ar?'اختار القسم ثم الخدمة وشوف التفاصيل قبل تأكيد الطلب.':'Choose a category, select a service and review the details before ordering.'}</p></div></div></div></section>
   <section className="landing-section"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><div className="landing-card"><Zap className="text-violet-600"/><h3 className="mt-5 font-black">{ar?'تنفيذ منظم':'Fast dispatch'}</h3><p className="landing-muted mt-2 text-sm">{ar?'الطلبات بتتوجه للمزودين المتصلين حسب إعدادات النظام.':'Orders can be routed to connected providers automatically.'}</p></div><div className="landing-card"><Wallet className="text-violet-600"/><h3 className="mt-5 font-black">{ar?'محفظة واضحة':'USD wallet'}</h3><p className="landing-muted mt-2 text-sm">{ar?'رصيدك وعملياتك في مكان واحد بعملة أساسية واضحة.':'Keep wallet balance and transactions in one clear base currency.'}</p></div><div className="landing-card"><Layers3 className="text-violet-600"/><h3 className="mt-5 font-black">{ar?'كتالوج متزامن':'Provider-ready'}</h3><p className="landing-muted mt-2 text-sm">{ar?'الخدمات والأسعار والحدود ممكن تتزامن من المزودين.':'Service names, prices, limits and capabilities can sync from providers.'}</p></div><div className="landing-card"><Headphones className="text-violet-600"/><h3 className="mt-5 font-black">{ar?'دعم وتذاكر':'Support'}</h3><p className="landing-muted mt-2 text-sm">{ar?'لو احتجت مساعدة، عندك قنوات دعم وتذاكر داخل المنصة.':'Use support channels and tickets when you need help.'}</p></div></div></section>
   <section className="bg-slate-950 text-white"><div className="landing-section grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-black tracking-[.16em] text-violet-300">{text.pricing}</p><h2 className="mt-3 text-white">{text.pricingCopy}</h2><Link to="/services" className="btn-primary mt-7">{text.openCatalog}<ArrowRight size={16}/></Link></div><div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]">{services.length?services.slice(0,6).map((s:any)=><div className="landing-price" key={s.id}><div className="min-w-0"><div className="truncate text-sm font-bold">{s.name}</div><div className="mt-1 text-[11px] text-slate-500">{s.category}</div></div><b className="shrink-0 text-sm">${Number(s.rate||0).toFixed(4)}</b></div>):<div className="p-8 text-center text-sm text-slate-500">{ar?'سيظهر الكتالوج هنا بعد توفر الخدمات.':'The live catalog will appear here when services are available.'}</div>}</div></div></section>
   <section className="landing-section"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="mb-2 text-xs font-black tracking-[.16em] text-violet-600">FAQ</p><h2>{text.faqTitle}</h2><p className="landing-muted mt-3">{text.faqCopy}</p></div><div className="landing-faq mt-8 rounded-3xl border border-slate-200 bg-white px-6 shadow-sm">{faqs.map(([q,a],i)=><div key={q} className="border-b border-slate-100 last:border-0"><button onClick={()=>setFaq(faq===i?-1:i)}><span>{q}</span><ChevronDown size={18} className={`shrink-0 text-slate-400 transition ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
   <section className="landing-section pt-0"><div className="landing-cta text-center"><ShieldCheck className="mx-auto"/><h2 className="mt-4 text-white">{text.ctaTitle}</h2><p className="mx-auto mt-3 max-w-xl text-violet-100">{text.ctaCopy}</p><button onClick={()=>setAuth('register')} className="btn-ghost mt-7 !border-0">{text.cta}<ArrowRight size={16}/></button></div></section>
  </main>
  {auth&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setAuth(null)}}><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl sm:p-8" dir={dir}><div className="mb-6 flex items-start justify-between"><div><span className="brand-mark">R</span><h2 className="mt-4 text-2xl font-black">{auth==='register'?text.registerTitle:text.loginTitle}</h2></div><button className="rounded-xl bg-slate-100 p-2" onClick={()=>setAuth(null)} aria-label={text.close}><X size={18}/></button></div><form onSubmit={handleAuth} className="space-y-4">{auth==='register'&&<div><label className="label-primary">{text.name}</label><input className="input-primary" value={name} onChange={e=>setName(e.target.value)} required/></div>}<div><label className="label-primary">{text.email}</label><input className="input-primary" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div><label className="label-primary">{text.password}</label><input className="input-primary" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></div>{auth==='login'&&<div className="text-right"><button type="button" onClick={handleReset} className="text-xs font-bold text-violet-600">{text.forgot}</button></div>}{auth==='register'&&<div><label className="label-primary">{text.ref} <span className="font-normal text-slate-400">({text.optional})</span></label><input className="input-primary" value={referralCode} disabled={!!referralFromUrl} onChange={e=>setReferralCode(e.target.value.toUpperCase())} placeholder="REF123"/><p className="mt-1 text-xs text-slate-500">{referralFromUrl?(ar?'الكود جاي من رابط الدعوة ومثبت.':'This code came from your invitation link and is locked.'):''}</p></div>}<button className="btn-primary w-full">{auth==='register'?text.submitRegister:text.submitLogin}</button></form><div className="mt-5 text-center text-sm text-slate-500">{auth==='register'?<>{text.already} <button className="font-bold text-violet-600" onClick={()=>setAuth('login')}>{text.login}</button></>:<>{text.newUser} <button className="font-bold text-violet-600" onClick={()=>setAuth('register')}>{text.start}</button></>}</div></div></div>}
 </div>
}
