import { Link, useParams } from 'react-router-dom';
import PublicPageShell from './PublicPageShell';
import SEO, { SITE } from '../components/SEO';
import { useTranslation } from '../lib/i18n';

const DATA: Record<string, { en: { name: string; title: string; description: string; keywords: string[]; intro: string; services: string[]; faq: [string,string][] }; ar: { name: string; title: string; description: string; keywords: string[]; intro: string; services: string[]; faq: [string,string][] } }> = {
  instagram: {
    en: { name:'Instagram', title:'Instagram SMM Services | Followers, Likes & Views | RapidSMM', description:'Instagram SMM services for followers, likes, views and engagement. Compare public pricing, minimums and available Instagram services.', keywords:['instagram smm panel','instagram services','instagram followers','instagram likes','instagram views','instagram marketing','buy instagram followers','buy instagram likes','instagram growth'], intro:'Explore Instagram-focused social media marketing services with clear pricing, order limits and service descriptions. Choose the service that matches your campaign and use the dashboard to place and track orders.', services:['Instagram Followers','Instagram Likes','Instagram Views','Instagram Comments','Instagram Reels Views','Instagram Story Views'], faq:[['What Instagram services are available?','The live catalog can include followers, likes, views, comments and other Instagram engagement services. Availability and pricing are shown on the public services page.'],['How do I order an Instagram service?','Create an account, add funds, select the Instagram category, choose a service, enter your public post or profile URL where applicable, and submit the quantity.']] },
    ar: { name:'إنستجرام', title:'خدمات إنستجرام SMM | متابعين ولايكات ومشاهدات | RapidSMM', description:'خدمات تسويق إنستجرام للمتابعين والإعجابات والمشاهدات والتفاعل، مع أسعار وحدود طلب واضحة وخدمات متاحة عبر لوحة RapidSMM.', keywords:['خدمات انستجرام','SMM انستجرام','متابعين انستجرام','لايكات انستجرام','مشاهدات انستجرام','تسويق انستجرام','زيادة متابعين انستجرام','لوحة SMM'], intro:'استكشف خدمات التسويق المتخصصة لإنستجرام مع أسعار واضحة والحد الأدنى والأقصى للطلبات ووصف كل خدمة. اختر الخدمة المناسبة لحملتك وتابع الطلب من لوحة التحكم.', services:['متابعين إنستجرام','لايكات إنستجرام','مشاهدات إنستجرام','تعليقات إنستجرام','مشاهدات ريلز','مشاهدات ستوري'], faq:[['ما هي خدمات إنستجرام المتاحة؟','قد يتضمن الكتالوج المتابعين واللايكات والمشاهدات والتعليقات وخدمات تفاعل أخرى. التوفر والأسعار الحالية تظهر في صفحة الخدمات.'],['كيف أطلب خدمة إنستجرام؟','أنشئ حساباً، اشحن الرصيد، اختر قسم إنستجرام، ثم اختر الخدمة وأدخل الرابط والكمية المطلوبة وأرسل الطلب.']] }
  },
  tiktok: {
    en: { name:'TikTok', title:'TikTok SMM Services | Followers, Likes & Views | RapidSMM', description:'TikTok SMM services for followers, likes and views with transparent pricing and order limits. Browse the available TikTok marketing catalog.', keywords:['tiktok smm panel','tiktok services','tiktok followers','tiktok likes','tiktok views','tiktok marketing','buy tiktok followers','buy tiktok likes','tiktok growth'], intro:'Build campaigns around TikTok followers, likes and views with a straightforward service catalog. Review the current rate, limits and description before ordering.', services:['TikTok Followers','TikTok Likes','TikTok Views','TikTok Comments','TikTok Shares','TikTok Live Engagement'], faq:[['What TikTok services can I order?','The catalog may include followers, likes, views, comments and other TikTok services depending on what is active.'],['Can I track my TikTok order?','Yes. Orders are visible in your dashboard with status updates and order details.']] },
    ar: { name:'تيك توك', title:'خدمات تيك توك SMM | متابعين ولايكات ومشاهدات | RapidSMM', description:'خدمات SMM لتيك توك للمتابعين واللايكات والمشاهدات بأسعار وحدود طلب واضحة. تصفح كتالوج خدمات تسويق تيك توك المتاح.', keywords:['خدمات تيك توك','SMM تيك توك','متابعين تيك توك','لايكات تيك توك','مشاهدات تيك توك','تسويق تيك توك','زيادة متابعين تيك توك'], intro:'ابنِ حملاتك على تيك توك باستخدام خدمات المتابعين واللايكات والمشاهدات مع كتالوج واضح. راجع السعر الحالي والحدود والوصف قبل تنفيذ الطلب.', services:['متابعين تيك توك','لايكات تيك توك','مشاهدات تيك توك','تعليقات تيك توك','مشاركات تيك توك','تفاعل تيك توك'], faq:[['ما خدمات تيك توك المتاحة؟','قد يشمل الكتالوج المتابعين واللايكات والمشاهدات والتعليقات وخدمات أخرى حسب الخدمات النشطة حالياً.'],['هل يمكن متابعة طلب تيك توك؟','نعم، تظهر الطلبات في لوحة التحكم مع الحالة وتفاصيل الطلب.']] }
  },
  youtube: {
    en: { name:'YouTube', title:'YouTube SMM Services | Views, Likes & Subscribers | RapidSMM', description:'YouTube marketing and SMM services for views, likes and subscribers. Browse available services, pricing and order limits.', keywords:['youtube smm panel','youtube services','youtube views','youtube subscribers','youtube likes','youtube marketing','buy youtube views','youtube promotion'], intro:'Find YouTube-focused services for channels and videos. Use the public catalog to review available rates, minimums and maximums before creating an account.', services:['YouTube Views','YouTube Subscribers','YouTube Likes','YouTube Comments','YouTube Watch Time'], faq:[['What YouTube services are available?','Depending on the active catalog, services can include views, subscribers, likes, comments and watch-time related services.'],['Where can I see current prices?','Current public pricing is listed on the Services & Pricing page.']] },
    ar: { name:'يوتيوب', title:'خدمات يوتيوب SMM | مشاهدات ولايكات ومشتركين | RapidSMM', description:'خدمات تسويق يوتيوب للمشاهدات واللايكات والمشتركين، مع عرض الخدمات والأسعار وحدود الطلب المتاحة.', keywords:['خدمات يوتيوب','SMM يوتيوب','مشاهدات يوتيوب','مشتركين يوتيوب','لايكات يوتيوب','تسويق يوتيوب','ترويج يوتيوب'], intro:'اكتشف الخدمات المتخصصة لقنوات وفيديوهات يوتيوب، وراجع الأسعار الحالية والحد الأدنى والأقصى قبل إنشاء الحساب.', services:['مشاهدات يوتيوب','مشتركين يوتيوب','لايكات يوتيوب','تعليقات يوتيوب','وقت مشاهدة يوتيوب'], faq:[['ما خدمات يوتيوب المتاحة؟','بحسب الكتالوج النشط قد تتوفر المشاهدات والمشتركين واللايكات والتعليقات وخدمات مرتبطة بوقت المشاهدة.'],['أين أرى الأسعار الحالية؟','الأسعار الحالية تظهر في صفحة الخدمات والأسعار العامة.']] }
  },
  facebook: {
    en: { name:'Facebook', title:'Facebook SMM Services | Likes, Followers & Engagement | RapidSMM', description:'Facebook SMM services for page likes, followers, post engagement and views. Review available services and transparent order limits.', keywords:['facebook smm panel','facebook services','facebook page likes','facebook followers','facebook post likes','facebook marketing','facebook promotion'], intro:'Browse Facebook-focused marketing services for pages and posts. Service availability, pricing and limits are shown in the public catalog.', services:['Facebook Page Likes','Facebook Followers','Facebook Post Likes','Facebook Post Views','Facebook Comments'], faq:[['Can I order Facebook page services?','Where active in the catalog, page likes and followers can be available alongside post engagement services.'],['How do I choose the right service?','Compare the service description, minimum, maximum and current rate before ordering.']] },
    ar: { name:'فيسبوك', title:'خدمات فيسبوك SMM | لايكات ومتابعين وتفاعل | RapidSMM', description:'خدمات SMM لفيسبوك تشمل لايكات الصفحات والمتابعين وتفاعل المنشورات والمشاهدات، مع حدود وأسعار واضحة.', keywords:['خدمات فيسبوك','SMM فيسبوك','لايكات فيسبوك','متابعين فيسبوك','تفاعل فيسبوك','تسويق فيسبوك','ترويج فيسبوك'], intro:'تصفح خدمات التسويق المتخصصة لفيسبوك للصفحات والمنشورات، مع عرض التوفر والسعر والحدود في الكتالوج العام.', services:['لايكات صفحات فيسبوك','متابعين فيسبوك','لايكات منشورات فيسبوك','مشاهدات منشورات فيسبوك','تعليقات فيسبوك'], faq:[['هل يمكن طلب خدمات صفحات فيسبوك؟','إذا كانت الخدمة نشطة في الكتالوج، يمكن أن تتوفر لايكات ومتابعون للصفحات بالإضافة إلى خدمات تفاعل المنشورات.'],['كيف أختار الخدمة المناسبة؟','قارن الوصف والحد الأدنى والأقصى والسعر الحالي قبل تنفيذ الطلب.']] }
  },
  telegram: {
    en: { name:'Telegram', title:'Telegram SMM Services | Members, Views & Engagement | RapidSMM', description:'Telegram marketing services for channel members, post views and engagement. Browse available Telegram services and pricing.', keywords:['telegram smm panel','telegram services','telegram members','telegram views','telegram marketing','buy telegram members','telegram promotion'], intro:'Grow and promote Telegram channels with services focused on members, post views and engagement. Check the live catalog before ordering.', services:['Telegram Members','Telegram Post Views','Telegram Reactions','Telegram Channel Promotion'], faq:[['What Telegram services are available?','The active catalog may include channel members, post views, reactions and other Telegram promotion services.'],['Are service limits shown?','Yes. Public service listings show minimum and maximum order quantities when available.']] },
    ar: { name:'تيليجرام', title:'خدمات تيليجرام SMM | أعضاء ومشاهدات وتفاعل | RapidSMM', description:'خدمات تسويق تيليجرام لأعضاء القنوات ومشاهدات المنشورات والتفاعل، مع عرض الخدمات والأسعار المتاحة.', keywords:['خدمات تيليجرام','SMM تيليجرام','أعضاء تيليجرام','مشاهدات تيليجرام','تسويق تيليجرام','ترويج تيليجرام'], intro:'روّج لقنوات تيليجرام بخدمات متخصصة للأعضاء ومشاهدات المنشورات والتفاعل. راجع الكتالوج الحالي قبل الطلب.', services:['أعضاء تيليجرام','مشاهدات منشورات تيليجرام','تفاعلات تيليجرام','ترويج قنوات تيليجرام'], faq:[['ما خدمات تيليجرام المتاحة؟','قد يتضمن الكتالوج الأعضاء ومشاهدات المنشورات والتفاعلات وخدمات ترويج أخرى.'],['هل تظهر حدود الطلب؟','نعم، تعرض قوائم الخدمات الحد الأدنى والأقصى عندما تكون البيانات متاحة.']] }
  },
  spotify: {
    en: { name:'Spotify', title:'Spotify Promotion & SMM Services | Plays & Followers | RapidSMM', description:'Spotify promotion services for plays, followers and music engagement. Review available Spotify services and order limits.', keywords:['spotify smm panel','spotify promotion','spotify plays','spotify followers','spotify music promotion','buy spotify plays'], intro:'Explore Spotify-focused promotion services for artists and music campaigns. Check current availability and service details before ordering.', services:['Spotify Plays','Spotify Followers','Spotify Saves','Spotify Playlist Promotion'], faq:[['What Spotify services may be available?','The catalog can include plays, followers, saves and other music promotion services when active.'],['Are prices live?','Yes. The public catalog is designed to show the current rate stored by the panel.']] },
    ar: { name:'سبوتيفاي', title:'خدمات ترويج سبوتيفاي SMM | تشغيلات ومتابعين | RapidSMM', description:'خدمات ترويج سبوتيفاي للتشغيلات والمتابعين والتفاعل الموسيقي، مع عرض الأسعار وحدود الطلب المتاحة.', keywords:['خدمات سبوتيفاي','ترويج سبوتيفاي','تشغيلات سبوتيفاي','متابعين سبوتيفاي','تسويق موسيقى سبوتيفاي'], intro:'اكتشف خدمات ترويج سبوتيفاي للفنانين والحملات الموسيقية، وراجع التوفر الحالي وتفاصيل الخدمة قبل الطلب.', services:['تشغيلات سبوتيفاي','متابعين سبوتيفاي','حفظ الأغاني على سبوتيفاي','ترويج قوائم سبوتيفاي'], faq:[['ما خدمات سبوتيفاي المتاحة؟','قد يشمل الكتالوج التشغيلات والمتابعين والحفظ وخدمات ترويج موسيقية أخرى عند توفرها.'],['هل الأسعار الحالية معروضة؟','نعم، صفحة الخدمات العامة تعرض السعر المخزن حالياً في اللوحة.']] }
  },
  twitter: {
    en: { name:'X / Twitter', title:'X Twitter SMM Services | Followers, Likes & Views | RapidSMM', description:'X and Twitter SMM services for followers, likes, views and engagement. Browse current services, pricing and limits.', keywords:['twitter smm panel','x smm panel','twitter followers','twitter likes','twitter views','x marketing','twitter promotion'], intro:'Find social media marketing services for X (formerly Twitter), including audience and engagement options where available in the catalog.', services:['X Followers','X Likes','X Views','X Reposts','X Comments'], faq:[['Is X the same as Twitter?','X is the current name of the platform formerly known as Twitter. Service availability depends on the active catalog.'],['Can I check service limits before ordering?','Yes. Public listings show minimum and maximum quantities where provided.']] },
    ar: { name:'إكس / تويتر', title:'خدمات X وتويتر SMM | متابعين ولايكات ومشاهدات | RapidSMM', description:'خدمات SMM لمنصة X وتويتر للمتابعين واللايكات والمشاهدات والتفاعل، مع عرض الأسعار والحدود المتاحة.', keywords:['خدمات تويتر','خدمات اكس','SMM تويتر','متابعين تويتر','لايكات تويتر','مشاهدات تويتر','تسويق اكس'], intro:'اكتشف خدمات التسويق لمنصة X (المعروفة سابقاً باسم Twitter)، مع خيارات الجمهور والتفاعل المتاحة في الكتالوج.', services:['متابعين X','لايكات X','مشاهدات X','إعادات نشر X','تعليقات X'], faq:[['هل X هو تويتر؟','X هو الاسم الحالي للمنصة التي كانت تُعرف باسم Twitter. توفر الخدمات يعتمد على الكتالوج النشط.'],['هل يمكن معرفة حدود الخدمة قبل الطلب؟','نعم، تعرض القوائم الحد الأدنى والأقصى عندما تكون البيانات متاحة.']] }
  },
  threads: {
    en: { name:'Threads', title:'Threads SMM Services | Followers, Likes & Views | RapidSMM', description:'Threads social media marketing services for followers, likes, views and engagement where available. Review pricing and order limits.', keywords:['threads smm panel','threads services','threads followers','threads likes','threads views','threads marketing','threads promotion'], intro:'Explore Threads-focused services for audience growth and engagement where the live catalog supports them. Review the current service details before ordering.', services:['Threads Followers','Threads Likes','Threads Views','Threads Reposts','Threads Comments'], faq:[['Are Threads services always available?','No. Availability depends on the live catalog. Only active services should be presented as orderable.'],['Where can I see all active services?','Use the public Services & Pricing page for the current catalog.']] },
    ar: { name:'ثريدز', title:'خدمات ثريدز SMM | متابعين ولايكات ومشاهدات | RapidSMM', description:'خدمات تسويق ثريدز للمتابعين واللايكات والمشاهدات والتفاعل عند توفرها، مع عرض الأسعار وحدود الطلب.', keywords:['خدمات ثريدز','SMM ثريدز','متابعين ثريدز','لايكات ثريدز','مشاهدات ثريدز','تسويق ثريدز'], intro:'استكشف خدمات ثريدز لزيادة الجمهور والتفاعل عند توفرها في الكتالوج، وراجع تفاصيل الخدمة الحالية قبل الطلب.', services:['متابعين ثريدز','لايكات ثريدز','مشاهدات ثريدز','إعادات نشر ثريدز','تعليقات ثريدز'], faq:[['هل خدمات ثريدز متاحة دائماً؟','لا، التوفر يعتمد على الكتالوج الحالي، ويجب أن تظهر فقط الخدمات النشطة القابلة للطلب.'],['أين أرى كل الخدمات النشطة؟','استخدم صفحة الخدمات والأسعار العامة لمشاهدة الكتالوج الحالي.']] }
  }
};

export default function PlatformSEO() {
  const { slug = 'instagram' } = useParams();
  const { lang } = useTranslation();
  const data = DATA[slug]?.[lang] || DATA.instagram.en;
  const path = `/${lang}/${slug}-services`;
  const faqSchema = data.faq.map(([q,a]) => ({ '@type':'Question', name:q, acceptedAnswer:{ '@type':'Answer', text:a } }));
  return <>
    <SEO title={data.title} description={data.description} path={path} keywords={data.keywords} lang={lang} alternates={{ ar: `/${'ar'}/${slug}-services`, en: `/${'en'}/${slug}-services`, xDefault: `/${'en'}/${slug}-services` }} jsonLd={[
      { '@context':'https://schema.org', '@type':'WebSite', name:'RapidSMM', url:SITE },
      { '@context':'https://schema.org', '@type':'Service', name:`${data.name} SMM Services`, description:data.description, provider:{ '@type':'Organization', name:'RapidSMM', url:SITE }, areaServed:'Worldwide', serviceType:'Social Media Marketing' },
      { '@context':'https://schema.org', '@type':'FAQPage', mainEntity:faqSchema }
    ]} />
    <PublicPageShell title={data.title}>
      <p className="text-base md:text-lg">{data.intro}</p>
      <section>
        <h2 className="text-xl font-bold text-white mb-3">{lang === 'ar' ? `خدمات ${data.name} المتخصصة` : `${data.name} services`}</h2>
        <div className="grid sm:grid-cols-2 gap-3">
          {data.services.map(s => <div key={s} className="rounded-xl border border-white/10 bg-white/[0.03] p-4 text-slate-200">{s}</div>)}
        </div>
      </section>
      <section>
        <h2 className="text-xl font-bold text-white mb-3">{lang === 'ar' ? 'الأسعار والتوفر' : 'Pricing & availability'}</h2>
        <p>{lang === 'ar' ? 'الأسعار والتوفر الفعليان يتغيران حسب الكتالوج النشط. راجع صفحة الخدمات العامة لمعرفة الخدمات المتاحة حالياً وحدود الطلب.' : 'Actual pricing and availability depend on the active catalog. Visit the public services page to see current services and order limits.'}</p>
        <Link to="/services" className="inline-flex mt-4 px-5 py-2.5 rounded-lg bg-amber-400 text-[#0B0F17] font-semibold">{lang === 'ar' ? 'عرض الخدمات والأسعار' : 'View services & pricing'}</Link>
      </section>
      <section>
        <h2 className="text-xl font-bold text-white mb-3">{lang === 'ar' ? 'الأسئلة الشائعة' : 'Frequently asked questions'}</h2>
        <div className="space-y-5">{data.faq.map(([q,a]) => <div key={q}><h3 className="font-semibold text-white">{q}</h3><p className="mt-1">{a}</p></div>)}</div>
      </section>
    </PublicPageShell>
  </>;
}
