import { useState } from 'react';
import toast from 'react-hot-toast';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useAuth } from '../../contexts/AuthContext';
import { apiFetch } from '../../lib/api';
import { Wallet, ShieldCheck, Bitcoin, ExternalLink } from 'lucide-react';

const walletMethods=[{value:'vf_cash',label:'Vodafone Cash',instruction:'بعد إنشاء الطلب، أكّد طلب الدفع من محفظتك/كود Vodafone Cash.'},{value:'or_cash',label:'Orange Cash',instruction:'بعد إنشاء الطلب، وافق على طلب الدفع من تطبيق Orange Cash.'},{value:'et_cash',label:'Etisalat Cash',instruction:'بعد إنشاء الطلب، وافق على طلب الدفع من e& Money / Etisalat Cash.'}];
export default function ClientAddFunds(){
 const {user}=useAuth(); const [gateway,setGateway]=useState<'wallet'|'crypto'>('wallet'); const [amount,setAmount]=useState<number|''>(''); const [walletMethod,setWalletMethod]=useState('vf_cash'); const [phoneNumber,setPhoneNumber]=useState(''); const [pendingPayment,setPendingPayment]=useState<any>(null); const [cryptoPayment,setCryptoPayment]=useState<any>(null);
 const {data:config}=useQuery({queryKey:['client-config'],queryFn:async()=>{const r=await apiFetch('/api/client/config',user);return r.ok?r.json():{};}});
 const walletPay=useMutation({mutationFn:async()=>{const t=await user?.getIdToken();const r=await apiFetch('/api/shahnawy/create',user,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({amount:Number(amount),number:phoneNumber,method:walletMethod})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||b.message||'Payment failed');return b;},onSuccess:b=>{setPendingPayment(b);toast.success('تم إنشاء طلب الدفع. أكّد العملية من محفظتك.');},onError:(e:any)=>toast.error(e.message)});
 const confirmWallet=useMutation({mutationFn:async()=>{const t=await user?.getIdToken();const r=await apiFetch('/api/shahnawy/confirm',user,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({paymentId:pendingPayment?.paymentId})});const b=await r.json().catch(()=>({}));if(!r.ok&&r.status!==202)throw new Error(b.error||b.message||'Confirmation failed');return b;},onSuccess:b=>{if(b.status==='completed'){toast.success('تم تأكيد الدفع وإضافة الرصيد.');setPendingPayment(null);setAmount('');setPhoneNumber('');}else toast('العملية ما زالت معلقة، جرّب التحقق مرة أخرى.');},onError:(e:any)=>toast.error(e.message)});
 const cryptoPay=useMutation({mutationFn:async()=>{const t=await user?.getIdToken();const r=await apiFetch('/api/heleket/create',user,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({amount:Number(amount)})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||b.message||'Crypto payment failed');return b;},onSuccess:b=>{setCryptoPayment(b);toast.success('تم إنشاء فاتورة Heleket.');},onError:(e:any)=>toast.error(e.message)});
 const rate=Number(config?.usdExchangeRate||0); const usdPreview=amount&&rate?Number(amount)/rate:null; const selected=walletMethods.find(x=>x.value===walletMethod)||walletMethods[0];
 return <div className="max-w-5xl mx-auto space-y-7"><div><h2 className="text-2xl font-bold text-gray-900">إضافة رصيد</h2><p className="text-sm text-gray-500 mt-1">اختر بين المحفظة الإلكترونية أو العملات الرقمية.</p></div>
 <div className="grid md:grid-cols-2 gap-4"><button onClick={()=>setGateway('wallet')} className={`rounded-2xl border-2 p-5 text-right ${gateway==='wallet'?'border-indigo-600 bg-indigo-50':'border-gray-200 bg-white'}`}><Wallet className="w-6 h-6 text-indigo-600 mb-2"/><b>المحفظة الإلكترونية</b><p className="text-xs text-gray-500 mt-1">Vodafone Cash / Orange Cash / Etisalat Cash</p></button><button onClick={()=>setGateway('crypto')} className={`rounded-2xl border-2 p-5 text-right ${gateway==='crypto'?'border-emerald-600 bg-emerald-50':'border-gray-200 bg-white'}`}><Bitcoin className="w-6 h-6 text-emerald-600 mb-2"/><b>العملات الرقمية — Heleket</b><p className="text-xs text-gray-500 mt-1">دفع تلقائي بفاتورة العملات الرقمية</p></button></div>
 {gateway==='wallet'&&<>{!config?.shahnawyEnabled?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4">المحافظ الإلكترونية غير متاحة حالياً.</div>:<div className="bg-white rounded-2xl border p-6 space-y-6"><div className="rounded-xl bg-indigo-50 p-4"><b>المحفظة الإلكترونية</b><p className="text-sm mt-1">أدخل رقم محفظتك الشخصية لاستقبال طلب الدفع على محفظتك.</p><p className="text-xs text-indigo-700 mt-1">العملية يتم التحقق منها تلقائياً قبل إضافة الرصيد.</p></div><div><label className="block text-sm font-medium mb-2">اختر المحفظة</label><div className="grid md:grid-cols-3 gap-3">{walletMethods.map(m=><button key={m.value} type="button" onClick={()=>setWalletMethod(m.value)} className={`p-4 rounded-xl border-2 text-right ${walletMethod===m.value?'border-indigo-600 bg-indigo-50':'border-gray-200'}`}><b>{m.label}</b><div className="text-xs text-gray-500 mt-1">دفع تلقائي</div></button>)}</div></div><div className="grid md:grid-cols-2 gap-5"><div><label className="block text-sm font-medium mb-1">المبلغ (EGP)</label><input type="number" min={config?.shahnawyMinAmount||5} max={config?.shahnawyMaxAmount||10000} value={amount} onChange={e=>setAmount(e.target.value===''?'':Number(e.target.value))} className="input-primary"/>{usdPreview!==null&&<p className="text-xs text-emerald-700 mt-2">سيضاف تقريباً <b>${usdPreview.toFixed(2)}</b>.</p>}</div><div><label className="block text-sm font-medium mb-1">رقم محفظتك</label><input type="tel" maxLength={11} value={phoneNumber} onChange={e=>setPhoneNumber(e.target.value.replace(/\D/g,'').slice(0,11))} className="input-primary" placeholder="01XXXXXXXXX"/></div></div><div className="rounded-xl border bg-gray-50 p-4 text-sm">{selected.instruction}</div><button onClick={()=>walletPay.mutate()} disabled={walletPay.isPending||!amount||!/^01\d{9}$/.test(phoneNumber)} className="w-full btn-primary py-3">{walletPay.isPending?'جاري إنشاء طلب الدفع...':'إنشاء طلب الدفع'}</button></div>}{pendingPayment&&<div className="bg-white rounded-2xl border border-emerald-200 p-6"><div className="flex gap-2 text-emerald-700 font-bold mb-3"><ShieldCheck/> طلب دفع قيد التأكيد</div><p className="text-sm">المبلغ: <b>{pendingPayment.amountEgp} EGP</b></p><p className="text-sm break-all">Reference: <b>{pendingPayment.reference||'-'}</b></p><div className="rounded-xl bg-amber-50 p-4 my-4 text-sm">{selected.instruction}</div><button onClick={()=>confirmWallet.mutate()} disabled={confirmWallet.isPending} className="w-full btn-primary">{confirmWallet.isPending?'جاري التحقق...':'تأكيد الدفع والتحقق من العملية'}</button></div>}</>}
 {gateway==='crypto'&&<div className="bg-white rounded-2xl border p-6 space-y-5"><div className="rounded-xl bg-emerald-50 p-4"><b>Heleket — العملات الرقمية</b><p className="text-sm text-gray-600 mt-1">المبلغ بالدولار، وبعد نجاح الدفع يتم إضافة الرصيد تلقائياً.</p></div><div><label className="block text-sm font-medium mb-1">المبلغ (USD)</label><input type="number" min="1" max="1000000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value===''?'':Number(e.target.value))} className="input-primary" placeholder="10"/></div><button onClick={()=>cryptoPay.mutate()} disabled={cryptoPay.isPending||!amount||!config?.heleketEnabled} className="w-full btn-primary py-3">{cryptoPay.isPending?'جاري إنشاء الفاتورة...':config?.heleketEnabled?'إنشاء فاتورة Heleket':'Heleket غير متاحة حالياً'}</button>{cryptoPayment&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><b className="text-emerald-800">فاتورة الدفع جاهزة</b><p className="text-sm my-3">افتح الفاتورة وأكمل الدفع. سيتم إضافة الرصيد تلقائياً بعد نجاح العملية.</p>{cryptoPayment.paymentUrl?<a href={cryptoPayment.paymentUrl} target="_blank" rel="noreferrer" className="btn-primary inline-flex items-center gap-2">فتح الفاتورة <ExternalLink className="w-4 h-4"/></a>:<p className="text-sm text-red-600">لم يتم استلام رابط الفاتورة.</p>}</div>}</div>}</div>;
}
