import { useState } from 'react';
import { useQuery, useQueryClient, useMutation } from '@tanstack/react-query';
import { useAuth } from '../../contexts/AuthContext';
import { apiFetch } from '../../lib/api';
import { Server, Plus, Trash2, X, RefreshCw, Pencil, Wifi, Wallet, SlidersHorizontal, CheckSquare } from 'lucide-react';
import toast from 'react-hot-toast';

async function readError(res: Response, fallback: string) { const d = await res.json().catch(() => ({})); return d?.error || d?.message || fallback; }

type Form = { name:string; apiUrl:string; apiKey:string; profitMargin:number; status:string };
const emptyForm:Form={name:'',apiUrl:'',apiKey:'',profitMargin:50,status:'active'};

export default function AdminProviders() {
  const { user } = useAuth(); const queryClient = useQueryClient();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null);
  const [form,setForm]=useState<Form>(emptyForm);
  const {data:providers=[],isLoading,isError,error}=useQuery({queryKey:['admin-providers'],enabled:!!user,queryFn:async()=>{const token=await user?.getIdToken();const r=await apiFetch('/api/admin/providers',user,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await readError(r,'Failed to load providers'));return r.json();}});
  const save=useMutation({mutationFn:async()=>{const token=await user?.getIdToken();const url=editing?`/api/admin/providers/${editing.id}`:'/api/admin/providers';const r=await apiFetch(url,user,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(form)});if(!r.ok)throw new Error(await readError(r,'Failed to save provider'));return r.json();},onSuccess:()=>{toast.success(editing?'Provider updated':'Provider added');setOpen(false);setEditing(null);setForm(emptyForm);queryClient.invalidateQueries({queryKey:['admin-providers']});},onError:(e:any)=>toast.error(e.message)});
  const remove=useMutation({mutationFn:async(id:string)=>{const token=await user?.getIdToken();const r=await apiFetch(`/api/admin/providers/${id}`,user,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await readError(r,'Failed to deactivate provider'));return r.json();},onSuccess:()=>{toast.success('Provider deactivated');queryClient.invalidateQueries({queryKey:['admin-providers']});},onError:(e:any)=>toast.error(e.message)});
  const startEdit=(p:any)=>{setEditing(p);setForm({name:p.name,apiUrl:p.apiUrl,apiKey:'',profitMargin:Number(p.profitMargin??50),status:p.status});setOpen(true);};
  return <div className="space-y-6">
    <div className="flex flex-wrap justify-between items-center gap-3"><div><h3 className="text-xl font-bold text-gray-900 flex items-center gap-2"><Server className="w-5 h-5"/> API Providers</h3><p className="text-sm text-gray-500 mt-1">تحكم كامل في الاتصال، الرصيد، المزامنة، والخدمات التابعة لكل مزود.</p></div><button type="button" onClick={()=>{setEditing(null);setForm(emptyForm);setOpen(true)}} className="btn-primary"><Plus className="w-4 h-4 mr-2 inline"/> Add Provider</button></div>
    {open&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form onSubmit={e=>{e.preventDefault();save.mutate()}} className="bg-white rounded-xl shadow-xl p-6 w-full max-w-lg space-y-4 max-h-[90vh] overflow-y-auto"><div className="flex justify-between items-center"><h4 className="text-lg font-bold">{editing?'Edit Provider':'Add Provider'}</h4><button type="button" onClick={()=>setOpen(false)}><X/></button></div><input required className="input-primary w-full" placeholder="Provider name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="url" className="input-primary w-full" placeholder="https://provider.example/api/v2" value={form.apiUrl} onChange={e=>setForm({...form,apiUrl:e.target.value})}/><input required={!editing} type="password" className="input-primary w-full" placeholder={editing?'API key (leave blank to keep current)':'API key'} value={form.apiKey} onChange={e=>setForm({...form,apiKey:e.target.value})}/><input required type="number" min="0" max="10000" className="input-primary w-full" placeholder="Profit margin %" value={form.profitMargin} onChange={e=>setForm({...form,profitMargin:Number(e.target.value)})}/><select className="input-primary w-full" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select><div className="flex gap-3 justify-end"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button disabled={save.isPending} className="btn-primary">{save.isPending?'Saving...':'Save'}</button></div></form></div>}
    {isError&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{(error as Error)?.message}</div>}
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[900px] w-full divide-y divide-gray-100"><thead className="bg-gray-50"><tr><th className="px-4 py-4 text-left text-xs font-semibold text-gray-500">Name</th><th className="px-4 py-4 text-left text-xs font-semibold text-gray-500">API URL</th><th className="px-4 py-4 text-left text-xs font-semibold text-gray-500">Balance</th><th className="px-4 py-4 text-left text-xs font-semibold text-gray-500">Margin</th><th className="px-4 py-4 text-left text-xs font-semibold text-gray-500">Status</th><th className="px-4 py-4 text-left text-xs font-semibold text-gray-500">Control</th></tr></thead><tbody className="bg-white divide-y divide-gray-100">{isLoading&&<tr><td colSpan={6} className="px-6 py-8 text-center">Loading...</td></tr>}{!isLoading&&!providers.length&&<tr><td colSpan={6} className="px-6 py-8 text-center text-gray-500">No providers found.</td></tr>}{providers.map((p:any)=><ProviderRow key={p.id} p={p} user={user} onEdit={()=>startEdit(p)} onDelete={()=>remove.mutate(p.id)} deleting={remove.isPending}/>)}</tbody></table></div></div>
  </div>;
}

function ProviderRow({p,user,onEdit,onDelete,deleting}:{p:any,user:any,onEdit:()=>void,onDelete:()=>void,deleting:boolean}){
  const queryClient=useQueryClient(); const [manage,setManage]=useState(false);
  const balance=useQuery({queryKey:['provider-balance',p.id],enabled:!!user,queryFn:async()=>{const token=await user?.getIdToken();const r=await apiFetch(`/api/admin/providers/${p.id}/balance`,user,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await readError(r,'Provider balance unavailable'));return r.json();}});
  const test=useMutation({mutationFn:async()=>{const token=await user?.getIdToken();const r=await apiFetch(`/api/admin/providers/${p.id}/test`,user,{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await readError(r,'Connection test failed'));return r.json();},onSuccess:d=>toast.success(`Connection OK${d.balance!=null?` — Balance: ${d.balance}`:''}`),onError:(e:any)=>toast.error(e.message)});
  const sync=useMutation({mutationFn:async()=>{const token=await user?.getIdToken();const r=await apiFetch(`/api/admin/providers/${p.id}/sync`,user,{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await readError(r,'Provider synchronization failed'));return r.json();},onSuccess:d=>{toast.success(`Synced ${d.synced??0} services — ${d.created??0} new / ${d.updated??0} updated`);queryClient.invalidateQueries({queryKey:['admin-services']});},onError:(e:any)=>toast.error(e.message)});
  return <><tr><td className="px-4 py-4 text-sm font-medium">{p.name}</td><td className="px-4 py-4 text-sm text-gray-500 max-w-xs truncate">{p.apiUrl}</td><td className="px-4 py-4 text-sm">{balance.isLoading?'...':balance.data?`${balance.data.balance??'0'} ${balance.data.currency||''}`:'Unavailable'}</td><td className="px-4 py-4 text-sm">{p.profitMargin}%</td><td className="px-4 py-4 text-sm"><span className={`px-2 py-1 rounded text-xs ${p.status==='active'?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-600'}`}>{p.status}</span></td><td className="px-4 py-4 text-sm"><div className="flex flex-wrap gap-2"><button type="button" onClick={onEdit} className="text-indigo-600 hover:underline"><Pencil className="w-4 h-4 inline mr-1"/>Edit</button><button type="button" onClick={()=>test.mutate()} disabled={test.isPending} className="text-emerald-600 hover:underline"><Wifi className="w-4 h-4 inline mr-1"/>{test.isPending?'Testing':'Test'}</button><button type="button" onClick={()=>sync.mutate()} disabled={sync.isPending} className="text-blue-600 hover:underline"><RefreshCw className="w-4 h-4 inline mr-1"/>{sync.isPending?'Syncing':'Sync'}</button><button type="button" onClick={()=>setManage(true)} className="text-purple-600 hover:underline"><SlidersHorizontal className="w-4 h-4 inline mr-1"/>Services</button><button type="button" onClick={()=>{if(confirm(`Deactivate ${p.name}?`))onDelete()}} disabled={deleting} className="text-red-600 hover:underline"><Trash2 className="w-4 h-4 inline mr-1"/>Deactivate</button></div></td></tr>{manage&&<ProviderServicesModal provider={p} user={user} onClose={()=>setManage(false)}/>}</>;
}

function ProviderServicesModal({provider,user,onClose}:{provider:any,user:any,onClose:()=>void}){
  const qc=useQueryClient(); const [selected,setSelected]=useState<string[]>([]); const [pct,setPct]=useState(''); const [status,setStatus]=useState('');
  const q=useQuery({queryKey:['provider-services',provider.id],enabled:!!user,queryFn:async()=>{const token=await user?.getIdToken();const r=await apiFetch(`/api/admin/providers/${provider.id}/services`,user,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await readError(r,'Failed to load provider services'));return r.json();}});
  const bulk=useMutation({mutationFn:async()=>{const token=await user?.getIdToken();const r=await apiFetch(`/api/admin/providers/${provider.id}/services/bulk`,user,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({serviceIds:selected,status:status||undefined,priceChangePercent:pct||undefined})});if(!r.ok)throw new Error(await readError(r,'Bulk update failed'));return r.json();},onSuccess:d=>{toast.success(`${d.changed} services updated`);q.refetch();qc.invalidateQueries({queryKey:['admin-services']});setSelected([]);},onError:(e:any)=>toast.error(e.message)});
  const rows=q.data||[]; const all=rows.length>0&&selected.length===rows.length;
  return <div className="fixed inset-0 z-[60] bg-black/50 flex items-center justify-center p-3"><div className="bg-white rounded-xl shadow-2xl w-full max-w-6xl max-h-[92vh] flex flex-col"><div className="p-4 border-b flex items-center justify-between"><div><h4 className="font-bold text-lg">{provider.name} — Service Control</h4><p className="text-xs text-gray-500">Select services, change status, or adjust selling price in bulk.</p></div><button onClick={onClose}><X/></button></div><div className="p-4 border-b flex flex-wrap gap-3 items-center"><button className="btn-secondary" onClick={()=>setSelected(all?[]:rows.map((r:any)=>r.id))}><CheckSquare className="w-4 h-4 inline mr-1"/>{all?'Clear':'Select all'}</button><select className="input-primary" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Keep status</option><option value="active">Activate</option><option value="inactive">Deactivate</option></select><input className="input-primary w-44" type="number" step="0.01" placeholder="Price change %" value={pct} onChange={e=>setPct(e.target.value)}/><button disabled={!selected.length||(!status&&!pct)||bulk.isPending} onClick={()=>bulk.mutate()} className="btn-primary">{bulk.isPending?'Updating...':`Apply to ${selected.length}`}</button></div><div className="overflow-auto flex-1"><table className="min-w-[850px] w-full"><thead className="sticky top-0 bg-gray-50"><tr><th className="p-3 text-left">Select</th><th className="p-3 text-left">Service</th><th className="p-3 text-left">Provider ID</th><th className="p-3 text-left">Selling / 1K</th><th className="p-3 text-left">Provider cost</th><th className="p-3 text-left">Status</th></tr></thead><tbody>{q.isLoading&&<tr><td colSpan={6} className="p-6 text-center">Loading services...</td></tr>}{!q.isLoading&&!rows.length&&<tr><td colSpan={6} className="p-6 text-center text-gray-500">No services are mapped to this provider yet. Run Sync first.</td></tr>}{rows.map((r:any)=><tr key={r.id} className="border-t"><td className="p-3"><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.id]:s.filter(x=>x!==r.id))}/></td><td className="p-3 text-sm">{r.name}</td><td className="p-3 text-sm">{r.providerServiceId||'-'}</td><td className="p-3 text-sm">{r.pricePer1k}</td><td className="p-3 text-sm">{r.providerPrice}</td><td className="p-3 text-sm">{r.status}</td></tr>)}</tbody></table></div><div className="p-4 border-t flex justify-end"><button className="btn-secondary" onClick={onClose}>Close</button></div></div></div>;
}
