import {useState,useEffect} from 'react'; import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'; import {ShieldAlert,Search,CheckCircle2} from 'lucide-react'; import { notify } from '../../lib/notify'; import {useAuth} from '../../contexts/AuthContext'; import {apiFetch} from '../../lib/api'; import AdminPagination from './AdminPagination';
const PAGE_SIZE=100;
export default function AdminSystemReports(){const{user}=useAuth();const qc=useQueryClient();const[q,setQ]=useState('');const[status,setStatus]=useState('all');const[page,setPage]=useState(1);
useEffect(()=>{setPage(1)},[status]);
const rQ=useQuery({queryKey:['admin-reports',page,status],enabled:!!user,queryFn:async()=>{const t=await user!.getIdToken();const params=new URLSearchParams({page:String(page),pageSize:String(PAGE_SIZE),status});const r=await apiFetch(`/api/admin/reports?${params}`,user,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error('Failed to load reports');return r.json()}});const resolve=useMutation({mutationFn:async(id:string)=>{const t=await user!.getIdToken();const r=await apiFetch(`/api/admin/reports/${id}/status`,user,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({status:'Resolved'})});if(!r.ok)throw new Error('Failed to resolve report');return r.json()},onSuccess:()=>{notify.success('Report resolved');qc.invalidateQueries({queryKey:['admin-reports']})},onError:(e:any)=>notify.error(e.message)});
const all=rQ.data?.data||[];const total=rQ.data?.total||0;
// Text search runs over the currently loaded page — narrow with the status filter first for a large history.
const rows=all.filter((r:any)=>`${r.action} ${r.location} ${r.errorReason}`.toLowerCase().includes(q.toLowerCase()));
return <div className="space-y-5"><div><h3 className="text-xl font-bold flex items-center gap-2"><ShieldAlert className="w-5 h-5"/>System Reports</h3><p className="text-sm text-gray-500">Search failures and mark handled incidents as resolved.</p></div><div className="bg-white border rounded-xl p-4 flex flex-wrap gap-3"><div className="relative flex-1 min-w-[220px]"><Search className="absolute left-3 top-3 w-4 h-4 text-gray-400"/><input className="input-primary pl-9" placeholder="Search this page: action, location or error" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input-primary w-auto" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="Unresolved">Unresolved</option><option value="Resolved">Resolved</option></select></div><div className="bg-white border rounded-xl overflow-x-auto"><table className="min-w-[1000px] w-full"><thead className="bg-gray-50"><tr>{['Date','Action','Location','Error / Reason','Status','Action'].map(h=><th key={h} className="px-4 py-3 text-left text-xs text-gray-500 uppercase">{h}</th>)}</tr></thead><tbody className="divide-y">{rQ.isLoading?<tr><td colSpan={6} className="p-8 text-center">Loading...</td></tr>:rows.map((r:any)=><tr key={r.id}><td className="px-4 py-3 text-xs">{new Date(r.createdAt).toLocaleString()}</td><td className="px-4 py-3 text-sm font-medium">{r.action}</td><td className="px-4 py-3 text-sm">{r.location}</td><td className="px-4 py-3 text-sm text-red-600">{r.errorReason}</td><td className="px-4 py-3 text-sm">{r.status}</td><td className="px-4 py-3">{r.status!=='Resolved'&&<button className="text-emerald-600" disabled={resolve.isPending} onClick={()=>resolve.mutate(r.id)}><CheckCircle2 className="w-4 h-4 inline mr-1"/>Resolve</button>}</td></tr>)}{!rQ.isLoading&&!rows.length&&<tr><td colSpan={6} className="p-8 text-center text-gray-500">No reports found.</td></tr>}</tbody></table><AdminPagination page={page} pageSize={PAGE_SIZE} total={total} onPageChange={setPage} /></div></div>}
