import {useEffect,useState} from 'react'; import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'; import {Search,RefreshCw,Download} from 'lucide-react'; import toast from 'react-hot-toast'; import {useAuth} from '../../contexts/AuthContext'; import {apiFetch} from '../../lib/api'; import AdminPagination from './AdminPagination';
const e=async(r:Response,f:string)=>{const b=await r.json().catch(()=>({}));return b?.error||f};
const PAGE_SIZE=100;
export default function AdminOrders(){const{user}=useAuth();const qc=useQueryClient();const[qInput,setQInput]=useState('');const[q,setQ]=useState('');const[status,setStatus]=useState('all');const[page,setPage]=useState(1);
useEffect(()=>{const t=setTimeout(()=>{setQ(qInput);setPage(1)},400);return()=>clearTimeout(t)},[qInput]);
useEffect(()=>{setPage(1)},[status]);
const oq=useQuery({queryKey:['admin-orders',page,q,status],enabled:!!user,refetchInterval:30000,queryFn:async()=>{const t=await user!.getIdToken();const params=new URLSearchParams({page:String(page),pageSize:String(PAGE_SIZE),status,...(q?{q}:{})});const r=await apiFetch(`/api/admin/orders?${params}`,user,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error(await e(r,'Failed to load orders'));return r.json()}});
const refresh=useMutation({mutationFn:async(id:string)=>{const t=await user!.getIdToken();const r=await apiFetch(`/api/admin/orders/${id}/refresh`,user,{method:'POST',headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error(await e(r,'Refresh failed'));return r.json()},onSuccess:()=>{toast.success('Order status refreshed');qc.invalidateQueries({queryKey:['admin-orders']})},onError:(x:any)=>toast.error(x.message)});
const rows=oq.data?.data||[];const total=oq.data?.total||0;
const csv=()=>{const out=['ID,User,Service,Quantity,Charge,Status,Provider Order ID,Created',...rows.map((o:any)=>[o.id,o.user?.email||'',o.service?.name||'',o.quantity,o.charge,o.status,o.providerOrderId||'',o.createdAt].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download=`admin-orders-page-${page}.csv`;a.click()};
return <div className="space-y-5"><div className="flex justify-between flex-wrap gap-3"><div><h3 className="text-xl font-bold">Order Control Center</h3><p className="text-sm text-gray-500">Search, filter, refresh provider status and export orders. Search matches order ID, link, or provider order ID.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>oq.refetch()}><RefreshCw className="w-4 h-4 inline mr-1"/>Refresh</button><button className="btn-secondary" onClick={csv}><Download className="w-4 h-4 inline mr-1"/>CSV (this page)</button></div></div><div className="bg-white border rounded-xl p-4 flex flex-wrap gap-3"><div className="relative flex-1 min-w-[220px]"><Search className="absolute left-3 top-3 w-4 h-4 text-gray-400"/><input className="input-primary pl-9" placeholder="Search order ID, link, provider ID..." value={qInput} onChange={x=>setQInput(x.target.value)}/></div><select className="input-primary w-auto" value={status} onChange={x=>setStatus(x.target.value)}><option value="all">All statuses</option>{['Pending','Processing','In Progress','Completed','Partial','Canceled','Refunded'].map(s=><option key={s}>{s}</option>)}</select></div><div className="bg-white border rounded-xl overflow-x-auto"><table className="min-w-[1100px] w-full"><thead className="bg-gray-50"><tr>{['ID','User','Service','Qty','Charge','Status','Provider ID','Actions'].map(h=><th key={h} className="px-4 py-3 text-left text-xs text-gray-500 uppercase">{h}</th>)}</tr></thead><tbody className="divide-y">{oq.isLoading?<tr><td colSpan={8} className="p-8 text-center">Loading...</td></tr>:rows.length?rows.map((o:any)=><tr key={o.id}><td className="px-4 py-3 font-mono text-xs">{o.id.slice(0,8)}</td><td className="px-4 py-3 text-sm">{o.user?.email||'-'}</td><td className="px-4 py-3 text-sm font-medium">{o.service?.name||'-'}</td><td className="px-4 py-3 text-sm">{o.quantity}</td><td className="px-4 py-3 text-sm">${Number(o.charge).toFixed(4)}</td><td className="px-4 py-3 text-sm">{o.status}</td><td className="px-4 py-3 text-xs font-mono">{o.providerOrderId||'-'}</td><td className="px-4 py-3">{o.providerOrderId&&<button className="text-indigo-600" disabled={refresh.isPending} onClick={()=>refresh.mutate(o.id)}><RefreshCw className="w-4 h-4 inline mr-1"/>Sync status</button>}</td></tr>):<tr><td colSpan={8} className="p-8 text-center text-gray-500">No orders found.</td></tr>}</tbody></table><AdminPagination page={page} pageSize={PAGE_SIZE} total={total} onPageChange={setPage} /></div></div>}
